@extends('layouts.dashboard')

@section('content')
<style>
    .attendance-hierarchy { --line: #e2e8f0; }
    .report-hierarchy-shell .report-card { border-radius: .75rem; }
    .report-hierarchy-shell .year-header { min-height: 5.25rem; padding: 1rem 1.25rem; }
    .report-hierarchy-shell .year-header h2 { font-size: 1rem; line-height: 1.5rem; font-weight: 700; }
    .report-hierarchy-shell .year-header p { font-size: .75rem; line-height: 1rem; }
    .report-hierarchy-shell .year-content { padding: 1rem; }
    .report-hierarchy-shell .month-link { min-height: 3.25rem; padding: .75rem 1rem; font-size: .875rem; line-height: 1.25rem; }
    .report-back-link { display: inline-flex; align-items: center; gap: .45rem; border: 1px solid #dbeafe; border-radius: .5rem; padding: .5rem .75rem; color: #2563eb; background: #eff6ff; font-size: .75rem; font-weight: 600; transition: background .15s ease, border-color .15s ease, transform .15s ease; }
    .report-back-link:hover { border-color: #93c5fd; background: #dbeafe; transform: translateX(-1px); }
    .attendance-hierarchy .report-card { border: 1px solid var(--line); box-shadow: 0 10px 30px rgba(15,23,42,.05); }
    .attendance-hierarchy .report-action { transition: transform .15s ease, box-shadow .15s ease; }
    .attendance-hierarchy .report-action:hover { transform: translateY(-1px); box-shadow: 0 5px 12px rgba(15,23,42,.12); }
    .attendance-hierarchy .month-link { border: 1px solid var(--line); transition: .15s ease; }
    .attendance-hierarchy .month-link:hover { border-color: #93c5fd; background: #eff6ff; transform: translateX(2px); }
    .attendance-hierarchy .row-actions { opacity: 0; pointer-events: none; transition: opacity .15s ease; }
    .attendance-hierarchy .month-link:hover .row-actions, .attendance-hierarchy .month-link:focus-within .row-actions { opacity: 1; pointer-events: auto; }
    .attendance-hierarchy .year-content.is-collapsed { display: none; }
    .attendance-hierarchy .year-header { cursor: pointer; user-select: none; }
    .attendance-hierarchy .year-header { position: relative; overflow: hidden; border-bottom-color: #dbeafe; background: linear-gradient(135deg, #ffffff 0%, #eff6ff 100%); }
    .attendance-hierarchy .year-header::before { content: ''; position: absolute; inset: 0 auto 0 0; width: .3rem; background: #2563eb; }
    .attendance-hierarchy .year-header > div:first-child { position: relative; }
    .attendance-hierarchy .year-header > div:first-child > span { display: inline-flex; height: 2.5rem; width: 2.5rem; align-items: center; justify-content: center; border-radius: .75rem; background: #dbeafe; color: #2563eb; }
    .attendance-hierarchy .year-header > div:first-child h2 { letter-spacing: .01em; }
    .attendance-hierarchy .year-header > div:first-child p { display: inline-flex; margin-top: .35rem; border-radius: 9999px; background: #f1f5f9; padding: .2rem .55rem; font-weight: 600; color: #64748b; }
    .attendance-hierarchy .year-chevron { transition: transform .2s ease; }
    .attendance-hierarchy .year-chevron.is-collapsed { transform: rotate(-90deg); }
    .attendance-hierarchy .sort-icon { display:inline-flex; height:2.25rem; width:2.25rem; align-items:center; justify-content:center; border:1px solid var(--line); border-radius:.6rem; color:#64748b; background:#fff; }
    .attendance-hierarchy .sort-icon:hover,.attendance-hierarchy .sort-icon.is-active { border-color:#93c5fd; background:#eff6ff; color:#2563eb; }
    .attendance-hierarchy a[href*="/attendance/summary/"] { display: none; }
    .attendance-hierarchy button[onclick*="add-attendance-month-"] { display: none; }
    .attendance-hierarchy form[id^="add-attendance-month-"] { display: none !important; }
    .attendance-hierarchy .attendance-year-card > .year-header > .flex.flex-wrap { display: none; }
    .attendance-hierarchy .month-link .row-actions { display: none; }
    .attendance-hierarchy a[href*="school-years"] { display: none; }
</style>
<div class="report-hierarchy-shell attendance-hierarchy flex flex-col gap-6">
    <div class="flex items-center justify-between gap-4"><div><a href="{{ route('admin.reports.sbfp.index') }}" class="report-back-link"><i class="fas fa-arrow-left"></i><span>Back</span></a><h1 class="mt-3 text-2xl font-bold text-slate-900">SBFP Attendance Report</h1><p class="mt-1 text-sm text-slate-500">Daily feeding attendance by school year and month.</p></div></div>
    @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><strong>Attendance action not completed</strong><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="flex flex-col gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row"><input id="attendanceSearch" type="search" placeholder="Search school year or month..." class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none sm:max-w-xs"><div class="flex items-center gap-1" aria-label="Sort school years"><button id="attendanceSortAsc" type="button" class="sort-icon" title="Oldest first" aria-label="Sort oldest first"><i class="fas fa-arrow-up"></i></button><button id="attendanceSortDesc" type="button" class="sort-icon is-active" title="Newest first" aria-label="Sort newest first"><i class="fas fa-arrow-down"></i></button></div><button id="attendanceToggle" type="button" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Collapse all</button></div>
    @forelse($schoolYears as $schoolYear)
        <section data-annual-year="{{ $schoolYear->year }}" class="attendance-year-card report-card overflow-visible rounded-xl bg-white">
            <div class="year-header flex flex-col gap-3 border-b border-slate-200 bg-slate-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between" tabindex="0" role="button" aria-expanded="true" aria-controls="attendance-content-{{ $schoolYear->id }}"><div class="flex items-center gap-3"><span class="p-1 text-slate-500"><i class="year-chevron fas fa-chevron-down"></i></span><div><h2 class="font-bold text-slate-900">SY {{ $schoolYear->year }}</h2><p class="text-xs text-slate-500">{{ $schoolYear->attendanceReportMonths->count() }} month(s)</p></div></div><div class="flex flex-wrap gap-2" onclick="event.stopPropagation()"><button type="button" onclick="document.getElementById('add-attendance-month-{{ $schoolYear->id }}').classList.toggle('hidden')" class="report-action rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white">+ Add Month</button><button type="button" onclick="document.getElementById('edit-attendance-year-{{ $schoolYear->id }}').classList.remove('hidden')" class="report-action rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white"><i class="fas fa-pen mr-1"></i>Edit</button><form method="POST" action="{{ route('admin.school-years.destroy', $schoolYear) }}" class="inline" onsubmit="return confirm('Delete this school year and all related records?')">@csrf @method('DELETE')<button type="submit" class="report-action rounded-lg bg-rose-600 px-3 py-2 text-xs font-semibold text-white" {{ $schoolYear->is_active ? 'disabled title=Activate another school year first' : '' }}><i class="fas fa-trash mr-1"></i>Delete</button></form></div></div>
            <div id="attendance-content-{{ $schoolYear->id }}" class="year-content">
                <form id="add-attendance-month-{{ $schoolYear->id }}" method="POST" action="{{ route('admin.reports.sbfp.attendance.months.store') }}" class="hidden flex flex-col gap-3 border-b border-slate-200 bg-blue-50 p-4 sm:flex-row sm:items-end">@csrf<input type="hidden" name="school_year_id" value="{{ $schoolYear->id }}"><div><label class="mb-1 block text-xs font-semibold text-slate-700">Month</label><select name="month" required class="rounded-lg border border-blue-200 bg-white px-3 py-2 text-sm">@foreach(range(1,12) as $month)<option value="{{ $month }}">{{ date('F', mktime(0,0,0,$month,1)) }}</option>@endforeach</select></div><button class="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white">Create Month</button></form>
                <div class="space-y-2 p-4">@forelse($schoolYear->attendanceReportMonths as $month)<div class="month-link flex items-center justify-between rounded-lg px-4 py-3 text-sm"><a href="{{ route('admin.reports.sbfp.attendance.month', $month) }}" class="flex flex-1 items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-blue-700"><i class="fas fa-calendar-day"></i></span><strong>{{ date('F', mktime(0,0,0,$month->month,1)) }}</strong><i class="fas fa-arrow-right ml-auto mr-3 text-slate-400"></i></a><div class="row-actions flex items-center gap-1"><button type="button" onclick="document.getElementById('edit-attendance-month-{{ $month->id }}').classList.remove('hidden')" class="rounded bg-amber-500 px-2 py-1 text-xs font-semibold text-white">Edit</button><form method="POST" action="{{ route('admin.reports.sbfp.attendance.month.destroy', $month) }}" onsubmit="return confirm('Delete this attendance month?')">@csrf @method('DELETE')<button class="rounded bg-rose-600 px-2 py-1 text-xs font-semibold text-white">Delete</button></form></div></div><div id="edit-attendance-month-{{ $month->id }}" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/40 p-4" onclick="if(event.target===this)this.classList.add('hidden')"><form method="POST" action="{{ route('admin.reports.sbfp.attendance.month.update', $month) }}" class="w-full max-w-sm rounded-xl bg-white p-6 shadow-2xl" onclick="event.stopPropagation()">@csrf @method('PATCH')<div class="mb-4 flex items-center justify-between"><div><h3 class="font-bold text-slate-900">Edit Attendance Month</h3><p class="mt-1 text-xs text-slate-500">Choose the month to replace.</p></div><button type="button" onclick="document.getElementById('edit-attendance-month-{{ $month->id }}').classList.add('hidden')"><i class="fas fa-times text-slate-400"></i></button></div><select name="month" required class="mb-5 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm">@foreach(range(1,12) as $option)<option value="{{ $option }}" {{ $month->month === $option ? 'selected' : '' }}>{{ date('F', mktime(0,0,0,$option,1)) }}</option>@endforeach</select><button class="w-full rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Save Month</button></form></div>@empty<p class="rounded-lg border border-dashed border-slate-200 px-5 py-5 text-sm text-slate-500">No attendance months created yet.</p>@endforelse<a href="{{ route('admin.reports.sbfp.attendance.summary', $schoolYear) }}" class="flex items-center justify-between rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800 hover:bg-blue-100"><span class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-blue-700"><i class="fas fa-chart-column"></i></span>Annual Summary</span><i class="fas fa-arrow-right text-blue-500"></i></a></div>
            </div>
            <div id="edit-attendance-year-{{ $schoolYear->id }}" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/40 p-4" onclick="if(event.target===this)this.classList.add('hidden')"><form method="POST" action="{{ route('admin.school-years.update', $schoolYear) }}" class="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl" onclick="event.stopPropagation()">@csrf @method('PATCH')<div class="mb-4 flex items-center justify-between"><h3 class="font-bold text-slate-900">Update School Year</h3><button type="button" onclick="document.getElementById('edit-attendance-year-{{ $schoolYear->id }}').classList.add('hidden')" aria-label="Close"><i class="fas fa-times text-slate-400"></i></button></div><input name="school_year" value="{{ $schoolYear->year }}" pattern="[0-9]{4}-[0-9]{4}" maxlength="9" required class="mb-3 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><input type="date" name="start_date" value="{{ optional($schoolYear->start_date)->format('Y-m-d') }}" required class="mb-3 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><input type="date" name="end_date" value="{{ optional($schoolYear->end_date)->format('Y-m-d') }}" class="mb-4 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><button class="w-full rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Save Update</button></form></div>
        </section>
    @empty
        <div class="report-card rounded-xl bg-white px-6 py-16 text-center"><i class="fas fa-calendar-alt text-4xl text-blue-200"></i><h2 class="mt-4 font-bold text-slate-800">No school years created</h2><p class="mt-1 text-sm text-slate-500">Create a school year before adding attendance months.</p><a href="{{ route('admin.school-years.index') }}" class="mt-5 inline-block rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Add School Year</a></div>
    @endforelse
</div>
<script>
const attendanceContainer=document.querySelector('.attendance-hierarchy');const attendanceCards=()=>[...attendanceContainer.querySelectorAll('.attendance-year-card')];const attendanceSearch=document.getElementById('attendanceSearch');const sortAttendance=(direction)=>{attendanceCards().sort((a,b)=>direction==='asc'?a.dataset.annualYear.localeCompare(b.dataset.annualYear):b.dataset.annualYear.localeCompare(a.dataset.annualYear)).forEach(c=>attendanceContainer.appendChild(c));document.getElementById('attendanceSortAsc').classList.toggle('is-active',direction==='asc');document.getElementById('attendanceSortDesc').classList.toggle('is-active',direction==='desc');};attendanceSearch?.addEventListener('input',()=>{const q=attendanceSearch.value.toLowerCase();attendanceCards().forEach(c=>c.hidden=!c.dataset.annualYear.toLowerCase().includes(q));});document.getElementById('attendanceSortAsc')?.addEventListener('click',()=>sortAttendance('asc'));document.getElementById('attendanceSortDesc')?.addEventListener('click',()=>sortAttendance('desc'));attendanceContainer.querySelectorAll('.year-header').forEach(header=>{const toggle=()=>{const content=document.getElementById(header.getAttribute('aria-controls'));const collapsed=content.classList.toggle('is-collapsed');header.setAttribute('aria-expanded',String(!collapsed));header.querySelector('.year-chevron').classList.toggle('is-collapsed',collapsed);};header.closest('.attendance-year-card').addEventListener('click',e=>{if(!e.target.closest('a,button,form,input,select,textarea,details,summary'))toggle();});header.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}});});document.getElementById('attendanceToggle')?.addEventListener('click',e=>{const collapse=e.target.textContent.trim()==='Collapse all';attendanceCards().forEach(c=>{c.querySelector('.year-content').classList.toggle('is-collapsed',collapse);c.querySelector('.year-chevron').classList.toggle('is-collapsed',collapse);});e.target.textContent=collapse?'Expand all':'Collapse all';});
</script>
<script>
    attendanceSearch?.addEventListener('input', () => {
        const query = attendanceSearch.value.trim().toLowerCase();
        attendanceCards().forEach((card) => {
            const yearMatches = card.dataset.annualYear.toLowerCase().includes(query);
            let monthMatches = false;
            card.querySelectorAll('.month-link').forEach((month) => {
                const matches = !query || yearMatches || month.textContent.toLowerCase().includes(query);
                month.hidden = !matches;
                monthMatches = monthMatches || matches;
            });
            card.hidden = !yearMatches && !monthMatches;
        });
    });
</script>
@endsection
