@extends('layouts.dashboard')

@section('content')
<style>
    .report-back-link { display: inline-flex; align-items: center; gap: .45rem; border: 1px solid #dbeafe; border-radius: .5rem; padding: .5rem .75rem; color: #2563eb; background: #eff6ff; font-size: .75rem; font-weight: 600; transition: background .15s ease, border-color .15s ease, transform .15s ease; }
    .report-back-link:hover { border-color: #93c5fd; background: #dbeafe; transform: translateX(-1px); }
    @media print {.sidebar,.sidebar-backdrop,.top-header,.no-print{display:none!important}.main-content{margin-left:0!important;width:100%!important}.content-body{padding:0!important}@page{size:landscape;margin:8mm}}
</style>
<div class="flex flex-col gap-5">
    <div class="no-print flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div><a href="{{ route('admin.reports.sbfp.index') }}" class="report-back-link"><i class="fas fa-arrow-left"></i><span>Back</span></a><h1 class="mt-3 text-xl font-bold text-gray-900">SBFP Assessment Report - SY {{ $assessment['school_year'] }}</h1><p class="text-xs text-gray-500">PROGRAM IMPACT | ATTENDANCE AND NUTRITION PROGRESS</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('admin.reports.sbfp.assessment.excel') }}" class="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><i class="fas fa-file-excel mr-1"></i> Excel</a><a href="{{ route('admin.reports.sbfp.assessment.docx') }}" class="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white"><i class="fas fa-file-word mr-1"></i> Word</a><a href="{{ route('admin.reports.sbfp.assessment.pdf') }}" class="rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white"><i class="fas fa-file-pdf mr-1"></i> PDF</a><a href="{{ route('admin.reports.sbfp.assessment.sql') }}" class="rounded-lg bg-slate-700 px-3 py-2 text-xs font-semibold text-white"><i class="fas fa-database mr-1"></i> SQL</a><button type="button" onclick="window.print()" class="rounded-lg bg-slate-200 px-3 py-2 text-xs font-semibold text-slate-700"><i class="fas fa-print mr-1"></i> Print</button></div>
    </div>
    <div class="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-bold text-slate-900">Student Attendance Summary</h2><p class="mt-1 text-xs text-slate-500">Students with recorded SBFP attendance</p></div><div class="text-right"><div class="text-2xl font-bold text-emerald-600">{{ $assessment['complete_attendance_rate'] }}%</div><div class="text-xs text-slate-500">complete</div></div></div><div class="mt-6 h-3 overflow-hidden rounded-full bg-rose-100"><div class="h-full bg-emerald-500" style="width: {{ $assessment['complete_attendance_rate'] }}%"></div></div><div class="mt-6 grid grid-cols-2 gap-4"><div class="border-l-4 border-emerald-500 pl-3"><div class="text-2xl font-bold text-slate-900">{{ $assessment['complete_attendance'] }}</div><div class="text-xs font-semibold uppercase tracking-wide text-slate-500">Complete attendance</div><div class="text-sm text-emerald-700">{{ $assessment['complete_attendance_rate'] }}%</div></div><div class="border-l-4 border-rose-500 pl-3"><div class="text-2xl font-bold text-slate-900">{{ $assessment['with_absences'] }}</div><div class="text-xs font-semibold uppercase tracking-wide text-slate-500">With absences</div><div class="text-sm text-rose-700">{{ $assessment['with_absences_rate'] }}%</div></div></div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-bold text-slate-900">SBFP Nutrition Progress</h2><p class="mt-1 text-xs text-slate-500">Baseline Wasted or Severely Wasted cohort</p></div><div class="text-right"><div class="text-2xl font-bold text-emerald-600">{{ $assessment['recovered_rate'] }}%</div><div class="text-xs text-slate-500">recovered</div></div></div><div class="mt-6 h-3 overflow-hidden rounded-full bg-amber-100"><div class="h-full bg-emerald-500" style="width: {{ $assessment['recovered_rate'] }}%"></div></div><div class="mt-6 grid grid-cols-2 gap-4"><div class="border-l-4 border-emerald-500 pl-3"><div class="text-2xl font-bold text-slate-900">{{ $assessment['recovered'] }}</div><div class="text-xs font-semibold uppercase tracking-wide text-slate-500">Recovered to Normal</div><div class="text-sm text-emerald-700">{{ $assessment['recovered_rate'] }}%</div></div><div class="border-l-4 border-amber-500 pl-3"><div class="text-2xl font-bold text-slate-900">{{ $assessment['still_needing_support'] }}</div><div class="text-xs font-semibold uppercase tracking-wide text-slate-500">Still needing support</div><div class="text-sm text-amber-700">{{ $assessment['still_needing_support_rate'] }}%</div></div></div></section>
    </div>
    <section class="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full border-collapse text-sm"><thead class="bg-slate-800 text-white"><tr><th class="border border-slate-600 px-4 py-3 text-left">Assessment Measure</th><th class="border border-slate-600 px-4 py-3 text-right">Count</th><th class="border border-slate-600 px-4 py-3 text-right">Percentage</th></tr></thead><tbody><tr><td class="border border-slate-200 px-4 py-3 font-semibold">Students with attendance records</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['attendance_students'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">100%</td></tr><tr><td class="border border-slate-200 px-4 py-3">Complete attendance</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['complete_attendance'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['complete_attendance_rate'] }}%</td></tr><tr><td class="border border-slate-200 px-4 py-3">With absences</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['with_absences'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['with_absences_rate'] }}%</td></tr><tr><td class="border border-slate-200 px-4 py-3 font-semibold">Baseline at-risk nutrition cohort</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['malnourished'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">100%</td></tr><tr><td class="border border-slate-200 px-4 py-3">Recovered to Normal</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['recovered'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['recovered_rate'] }}%</td></tr><tr><td class="border border-slate-200 px-4 py-3">Still needing support</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['still_needing_support'] }}</td><td class="border border-slate-200 px-4 py-3 text-right">{{ $assessment['still_needing_support_rate'] }}%</td></tr></tbody></table></section>
</div>
@endsection
